name: neobildOS-Release-Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: android-actions/setup-android@v3
      - run: |
          mkdir build && cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-34 -DANDROID_STL=c++_static \
            -DCMAKE_BUILD_TYPE=Release -DGGML_OPENCL=OFF -DGGML_NATIVE=OFF -DBUILD_SHARED_LIBS=OFF
          make -j4 llama-bench llama-cli
      - uses: actions/upload-artifact@v4
        with:
          name: neobildOS-binaries
          path: build/bin/
